### ISSUE TITLE
SMTP initializationf fails

### ISSUE THREAD

**Issue by pblxptr** [paralin/sendgmailapi#7]
I would like to report that it does not work.
I'm getting an error "Unable to initialize SMTP properly. Check config and use --smtp-debug. VALUES:"
I've already tried changing tls to ssl and vice versa. I do not use any firewall (I'm not using corporate network and so on). The Google configuration is fine because I'm getting the right token.
Ubuntu 22.04

**Comment by paralin** [comment]
Where is that error coming from? Git? Smtp shouldn't be used at all. I think your Git config is not set properly to run the send email helper.

**Comment by paralin** [comment]
Your .gitconfig should have this (and only this, no other smtp options).

```
[sendemail]
  smtpServer = /Users/myuser/go/bin/sendgmailapi
```
